spring:
  datasource:
    url: jdbc:h2:mem:project2
    username: zernov
    initialization-mode: never

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

    show-sql: true

logging:
  level:
    ROOT: ERROR